"""Pydantic contracts — the spine of the system (TS §4)."""

from xlforecast.schemas.artifacts import (
    MAX_ARTIFACT_POINTS,
    Analogue,
    ArtifactPack,
    Attribution,
    CalendarContext,
    Decomposition,
    PeakDrop,
    UncertaintyContext,
)
from xlforecast.schemas.enums import (
    EnsembleMethod,
    ExclusionReason,
    Family,
    GapFill,
    InformationSet,
    IntermittencyClass,
    ProbEnsembleMethod,
    Quantity,
    Scope,
    SelectionStrategy,
)
from xlforecast.schemas.freq import default_season_length, normalise_freq
from xlforecast.schemas.profile import DataProfile, SeriesProfile, ValidationReport
from xlforecast.schemas.registry import DEFAULT_MODELS, MODEL_REGISTRY, ModelSpec
from xlforecast.schemas.request import (
    DataMapping,
    ExogSpec,
    ForecastRequest,
    ModelName,
    ResolvedRequest,
)
from xlforecast.schemas.results import (
    ConformalBands,
    FoldScore,
    ForecastFrame,
    ForecastRow,
    Leaderboard,
    LeaderboardRow,
    Manifest,
    ModelTiming,
    RunResult,
    RunTiming,
)

__all__ = [
    "DEFAULT_MODELS",
    "MAX_ARTIFACT_POINTS",
    "MODEL_REGISTRY",
    "Analogue",
    "ArtifactPack",
    "Attribution",
    "CalendarContext",
    "ConformalBands",
    "DataMapping",
    "DataProfile",
    "Decomposition",
    "EnsembleMethod",
    "ExclusionReason",
    "ExogSpec",
    "Family",
    "FoldScore",
    "ForecastFrame",
    "ForecastRequest",
    "ForecastRow",
    "GapFill",
    "InformationSet",
    "IntermittencyClass",
    "Leaderboard",
    "LeaderboardRow",
    "Manifest",
    "ModelName",
    "ModelSpec",
    "ModelTiming",
    "PeakDrop",
    "ProbEnsembleMethod",
    "Quantity",
    "ResolvedRequest",
    "RunResult",
    "RunTiming",
    "Scope",
    "SelectionStrategy",
    "SeriesProfile",
    "UncertaintyContext",
    "ValidationReport",
    "default_season_length",
    "normalise_freq",
]
