import { readFileSync } from "node:fs";
import { defineConfig } from "vite";

/**
 * Office loads the pane as a plain web page, so the bundle is a self-contained ES module
 * served over HTTPS. No framework: the pane is five states and a form.
 *
 * Two dev-server decisions exist to avoid problems that look like add-in bugs but are not:
 *
 * - **HTTPS is mandatory.** Office refuses to load a task pane over HTTP, and the failure
 *   presents as "the add-in won't load" with nothing useful in any log. The certificate comes
 *   from `office-addin-dev-certs`, which installs a locally trusted CA; a self-signed
 *   certificate produces the same silent refusal.
 * - **The API is proxied under the same origin.** Serving the pane from
 *   `https://localhost:3000` and the API from `http://localhost:8000` would be both mixed
 *   content and cross-origin, so the browser blocks it and the session cookie is never sent.
 *   Proxying `/v1` makes everything same-origin, which is also how it is deployed.
 */

function devCertificate(): { key: Buffer; cert: Buffer } | undefined {
  // Generated by `npm run certs`. Absent on CI, where only `vite build` runs.
  try {
    const home = process.env["HOME"] ?? process.env["USERPROFILE"] ?? "";
    const dir = `${home}/.office-addin-dev-certs`;
    return {
      key: readFileSync(`${dir}/localhost.key`),
      cert: readFileSync(`${dir}/localhost.crt`),
    };
  } catch {
    return undefined;
  }
}

const certificate = devCertificate();

export default defineConfig({
  server: {
    port: 3000,
    strictPort: true,
    ...(certificate ? { https: certificate } : {}),
    proxy: {
      "/v1": {
        target: process.env["XLF_API"] ?? "http://localhost:8000",
        changeOrigin: false,
        secure: false,
      },
    },
  },
  build: {
    target: "es2022",
    outDir: "dist",
    rollupOptions: { input: { taskpane: "src/taskpane.html" } },
  },
  test: {
    globals: true,
    environment: "node",
    include: ["test/**/*.test.ts"],
    coverage: { include: ["src/**/*.ts"], exclude: ["src/taskpane.ts"] },
  },
});
